name: Sync ultraman_cards.csv to DB
on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Pull external file
        run: |
          curl -o ultraman_cards.csv \
          https://raw.githubusercontent.com/QueenLinuxGlitch/ultraman-card-db-api/refs/heads/main/ultraman_cards.csv

      - name: Sync DB
        run: python update_card_db.py

      - name: Commit changes if any
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add ultraman_cards.csv
          git commit -m "Sync Cards CSV" || echo "No changes"
          git push
