name: News!

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  check_news:
    runs-on: ubuntu-latest
    environment: Production
    env:
      NEWS_WEBHOOK: ${{ secrets.NEWS_WEBHOOK }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests feedparser

      - name: Run monitor
        run: |
          python discord-scripts/u-connection-rss.py

      - name: Commit changes if any
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add discord-scripts/last_rss_uc_item.json
          git commit -m "New RSS items" || echo "No changes"
          git push
